feature: #100 Distribute Goxygen as a Docker image
Shpota/goxygen pull request #108
Opened 2022-02-06 16:07 UTC by orgmatileg

Hi I just made changes for #100 distributing Goxygen to GitHub Packages Docker

What changes will happen:
- When the branch master has a new commit, GitHub Action `docker-build-package` will trigger and create an image and push as `ghcr.io/orgmatileg/goxygen:latest`
- When a new tag is created GitHub Action `docker-build-package` will trigger and create an image and push as `ghcr.io/orgmatileg/goxygen:{new tag name}`

2022-02-15 04:46 UTC, orgmatileg commented
Hi, Gentle reminder to review the PR.. thanks!

Have a nice day

2022-02-16 19:46 UTC, Shpota commented
I am sorry for the delay @orgmatileg, I am quite busy these days. I would need to try out, run, and foremost to understand your code, which requires time. I'll review it once I find time (hopefully this week).

2022-04-16 21:27 UTC, Shpota requested changes
Thank you for submitting this pull request!
I am sorry for not reviewing it for so long. With the war in my country, I didn't have time for open source. I added a couple of comments suggesting improvements. Let me know what you think.

2022-04-16 21:27 UTC, Shpota commented on Dockerfile
> +FROM golang:1.17.6-bullseye
1. I would suggest using an alpine-based image instead (with git on top of it). The bullseye image takes up almost 1GB in comparison with 329Mb of an alpine one.
2. Let's use a multistage docker build. After a Goxygen binary is built, we don't need its source code in the image as well as the Go compiler, and executor. You can copy the `/app/goxygen` to the new image (an alpine-based one). In the end, the image would be only 24Mb in size.

2022-04-16 21:27 UTC, Shpota commented on Dockerfile
> +RUN git config --global user.email "arlhba@gmail.com" && git config --global user.name "Luqmanul Hakim"
I would suggest using a non-existing email for code generation. Eg: `goxygen@noreply.github.com` with name set as `Goxygen`.

If you want to preserve attribution in the image, you can add a label that would end up in the image metadata once it is pushed:
```
LABEL org.opencontainers.image.authors="arlhba@gmail.com"
```

2022-04-16 21:27 UTC, Shpota commented on Dockerfile
> +
I would suggest relapsing three empty lines with one.

2022-04-16 21:27 UTC, Shpota commented on Dockerfile
> +ENV GOXYGEN_DOCKER=true
I don't quite understand why this part is needed (as well as the corresponding changes in the Go code).

I have tested and the following command would correctly do what we need (given there is a symlink to goxygen executable and the workdir of an image is set to `/app`):
```
docker run --rm -it -v $(pwd):/app image-tag goxygen init my-app
```

Let's optimize it.

2022-04-16 21:27 UTC, Shpota commented on Dockerfile
> +# Without this line, the docker image will not be able to run and produce error:
Let's remove these comments. I guess it is fine considering the app is supposed to generate a Git repository.

2022-04-16 21:27 UTC, Shpota commented on .github/workflows/docker-build-package.yml
> +      - name: Push image
I didn't test this part yet. Can you please tell me what tags would it produce and for what conditions? I want to make sure I understand the code correctly.

2022-12-03 17:43 UTC, Shpota commented
Thank you for the pull request.

For go 1.17+ the user can run `go run package@version` syntax which removes the need of having a Docker image for generating a project. I believe it is sufficient.

Closing this PR.

2022-12-03 17:43 UTC, closed without merging