transform: fix module path
Shpota/goxygen pull request #129
Opened 2023-07-17 15:40 UTC by dolmen

We are not Go stdlib. Use a module path `github.com/shpota/goxygen/transform` instead of just `transform`.

2023-07-17 18:26 UTC, Shpota requested changes

2023-07-17 18:26 UTC, Shpota commented on transform/go.mod
> +module github.com/shopta/goxygen/transform
This one has a typo

```suggestion
module github.com/shpota/goxygen/transform
```

2023-07-18 21:42 UTC, dolmen commented on transform/go.mod
> +module github.com/shopta/goxygen/transform
Oups.

2023-07-20 09:02 UTC, dolmen commented on transform/go.mod
> +module github.com/shopta/goxygen/transform
Fixed.

2023-07-20 09:04 UTC, dolmen commented
@Shpota Everything fixed. Branch rebased.

2023-07-20 09:09 UTC, Shpota approved these changes

2023-07-20 09:12 UTC, Shpota commented
Thank you, merged!

2023-07-20 09:12 UTC, merged